### ISSUE TITLE
Support more properties associated with JabRef

### ISSUE THREAD

**Issue by wenlzhang** [hans/obsidian-citation-plugin#100]
From the BibTeX file created with JabRef, one may define custom fields like comment, groups, ranking, priority, timestamp, etc. Is it possible to support inserting these properties in the template when creating literature notes?

**Comment by hans** [comment]
Hi @wenlzhang , this isn't documented, but you should have easy access to any custom fields via the `entry` object, e.g.

```
{{entry.data.fields.comment}}
```
