### ISSUE TITLE
Citations plug in not working with iPadOS

### ISSUE THREAD

**Issue by fredriksy** [hans/obsidian-citation-plugin#105]
Currently on the mobile version of Obsidian on my iPadOS, an error is thrown when trying to load Citations.

How to test:  Load up Obsidian on iPadOS
Observation: Says Failed to load plugin obsidian-citations-plugin
expected behaviour, plug in loads properly

**Comment by mcndt** [comment]
@hans in case you rely on dekstop only APIs, you might want to set ´isDesktopOnly´ to true in the Obsidian manifest file so the plugin stops being loaded on mobile.

**Comment by torralbofco** [comment]
Same problem as fredriksy. After opening Obsidian in iPadOS, citation plugin is disable and I have to enable again back on my desktop.

**Comment by hans** [comment]
Hi, thanks for reporting and thanks @mcndt for the tip. This will be fixed in the next release -- we will explicitly not support mobile Obsidian.
