### ISSUE TITLE
Feature Request: Access to {{file}} field of a BibTeX entry, to auto-link to the PDF file

### ISSUE THREAD

**Issue by davidromerot** [hans/obsidian-citation-plugin#108]
First of all, let me thank you for this wonderful plugin.

The desired feature is the ability to insert a citation note (Ctrl-Shift-E) and having the new notes page include a link to the content of the "files" or "file" field in the BibTeX entry. This way there will be a hard link between the notes about a citation and the actual PDF file that the citation is about.

I was trying to play with the {{entry}} object in the notes template, but was unable to access the file field. Any ideas?

Given that there is already access to many other fields, e.g. {{author}}, {{year}}, etc., it shouldn't be too difficult to add the link to the file if that information is available in the BiBTeX database.

Thanks!

**Comment by wenlzhang** [comment]
Maybe this is related:
[Wiki-request: How to open PDF of article within Obsidian · Issue #69 · hans/obsidian-citation-plugin](https://github.com/hans/obsidian-citation-plugin/issues/69)

**Comment by hans** [comment]
Hi, you can use the template `{{entry.files}}` to access this value. This isn't provided as a top-level variable because it is only supported in some citation database formats (like BibLaTeX).

Feel free to use Handlebars templating to do something fancy, e.g.
```
{{#each entry.files}}
- [PDF link]({{this}})
{{/each}}
