### ISSUE TITLE
Plugin cannot be enabled after installation

### ISSUE THREAD

**Issue by stefanocoretta** [hans/obsidian-citation-plugin#112]
This looks like an awesome plugin! I tried to install it but after installation, if I click on `Enable`, this message is returned:

```
Failed to load plugin obsidian-citation-plugin
```

OS: macOS 11.5 (20G71)
Obsidian: 1.0.4 (21)

<img width="1509" alt="Failed to load plugin" src="https://user-images.githubusercontent.com/6429302/129440202-596789f9-df57-4354-bc35-ca5ecedfa542.png">

**Comment by stefanocoretta** [comment]
Never mind... 😣😓 I installed the iPad version on macOS...

**Comment by abhyantrika** [comment]
Genuine issue.
