### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by abhyantrika** [hans/obsidian-citation-plugin#113]
```Failed to load plugin```

OS: Big Sur 11.5.2

Plugin installs, but fails to switch on.

**Comment by hans** [comment]
Hi, can you open the Obsidian developer console (Ctrl+Shift+I) , reload obsidian (Ctrl+R), then attempt to switch on the plugin again? Please watch the console (in the lower right) and let me know if you see any error messages appear here. Thanks!

Also, what version of Obsidian are you using?

**Comment by abhyantrika** [comment]
Oh. 
I had downloaded it from App Store. That's very weird from Apple. 
Works fine now.
