### ISSUE TITLE
The {{note}} field isn't replaced with the Zotero entry notes

### ISSUE THREAD

**Issue by puffitos** [hans/obsidian-citation-plugin#115]
**Describe the bug**
Accessing the `note` property of an Entry object, which I suppose is a Zotero entry, returns nothing. My aim is to access my extracted annotations from the Zotero entry directly, so I don't have to manually copy them each time I create a literature note. The annotations are extracted using the Zotfile plugin.

**To Reproduce**
1. Create a literature note based on a template, which contains the {{note}} field.
2. The note is successfully created, open the note to check whether my annotations are there as well.
2. All other fields, like {{title}} or {{doi}} are successfully read and replaced, but the {{note}} field isn't.  

**Console output**
No console output.

**Expected behavior**
I expected my annotation note to appear in the Obsidian note, where the {{note}} field is.

**Screenshots**
The template I'm using (only the part with the {{note}} field). I've also tried including the Entry.note, but to no avail:
![image](https://user-images.githubusercontent.com/52347078/131381947-fd7ebd48-3229-4ead-83df-b8862f42fec9.png)

The Zotero item I'm trying to create a literature note on:
![image](https://user-images.githubusercontent.com/52347078/131382224-90d48184-7965-489d-a86a-4f480008304a.png)

The created Obsidian note:
![image](https://user-images.githubusercontent.com/52347078/131382354-fc3bcdee-a58f-47e4-9639-da83b9f1660f.png)

**Platform**
 - OS: Ubuntu 20.04
 - Obsidian version: 0.12.12
 - Plugin Version: 0.4.4

**Comment by brozena** [comment]
Heavy {{note}} user here. Curious where this thread goes.

@puffitos wanted to clarify -- you extracted the annotations prior to creating the lit note? My experience with {{note}} is that it reads it on note creation, but maybe it doesn't update given new annotations. Happy to be wrong.

It sure would be nice for it to somehow update {{note}} given new zotfile extractions.

**Comment by puffitos** [comment]
Yeah the annotations were extracted _prior_ to creating the note for the Zotero entry in Obisian. Unfortunately they aren't copied into Obsidian automatically, as is the expected behavior; at least according to my understanding :sweat_smile:

**Comment by hans** [comment]
Hi @puffitos , would you mind sharing the relevant export data (BibLaTeX entry, or excerpt of CSL-JSON file) for a citation exhibiting this bug (e.g. the Hoffmann 2018 entry)?

**Comment by puffitos** [comment]
Hi @hans, thanks for the quick answer!

The bib entry for the book in question:
```
@book{hoffmannTheoretischeInformatikMit2018,
  title = {Theoretische {{Informatik}}: Mit 295 {{Bildern}}, 26 {{Tabellen}} Und 109 {{Aufgaben}}},
  shorttitle = {Theoretische {{Informatik}}},
  author = {Hoffmann, Dirk W.},
  year = {2018},
  edition = {4., aktualisierte Auflage},
  publisher = {{Hanser}},
  address = {{M\"unchen}},
  abstract = {\$uEinf\"uhrung -- Mathematische Grundlagen -- Logik und Deduktion -- Formale Sprachen -- Endliche Automaten -- Berechenbarkeitstheorie -- Komplexit\"atstheorie},
  isbn = {978-3-446-45793-5},
  language = {en},
  file = {PATH_TO_PDF}
}
```

I'll try with a couple more books and see whether file location is maybe mucking things up.

**Comment by puffitos** [comment]
I feel so stupid not having though of this, but the culprit was the Better BibTeX plugin in Zotero...

I took a look into its settings and found out, that one must explicitely enable the "Export Notes" functionality (see screenshot). I turned on the Zotero debugger and tried to do the export via Mdnotes and a certain line in the log seemed relevant:
> "exportNotes":false,"

So I went to the Advanced Settings of better bibtex and there it was, plain as day:
![image](https://user-images.githubusercontent.com/52347078/131543795-887e4481-3ca0-4380-a862-6e2b30333fa8.png)

The only problem I'm having ATM is that `>` characters in the extracted annotations are being parsed as `&gt;` into Obsidian.
The fun never ends! :)

**Comment by hans** [comment]
Hi @puffitos , glad you found the solution and thanks for reporting here!

> `>` characters in the extracted annotations are being parsed as &gt; into Obsidian.

This is because the templating system automatically escapes potentially HTML-unsafe characters (`<`,`>`,`"`,`'`, etc.). But things should look fine in Obsidian's Preview mode.

Is this a problem for you? Do you have HTML notes that are getting destroyed by the escaping procedure here? (I don't actually use Zotero notes -- are they HTML?) If so, we might need to take a cue from mdnotes and convert the note contents to Markdown before templating.

**Comment by puffitos** [comment]
Yeah it's become a major nuisance the last couple of days, because I want an automated workflow of extracting the notes I make on papers/ books into a markdown friendly format (for Obsidian). 

The notes in Zotero are HTML, yes. A snippet from a Zotero note:
```html
<blockquote>
<p>sdadsafsf</p>
</blockquote>
<p>PRIME und SAT sind exponenziall ybd gelten in der Praxis als nicht lösbar. (<a href="zotero://open-pdf/library/items/VAB33DNE?page=30">note on p.30</a>)</p>
```
This gets exported in the .bib file (Better BibLaTeX format chosen) as follows:
```
@book{hoffmannTheoretischeInformatikMit2018,
  title = {Theoretische {{Informatik}}: Mit 295 {{Bildern}}, 26 {{Tabellen}} Und 109 {{Aufgaben}}},
  shorttitle = {Theoretische {{Informatik}}},
  author = {Hoffmann, Dirk W.},
  date = {2018},
  edition = {4., aktualisierte Auflage},
  publisher = {{Hanser}},
  location = {{M\"unchen}},
  abstract = {\$uEinf\"uhrung -- Mathematische Grundlagen -- Logik und Deduktion -- Formale Sprachen -- Endliche Automaten -- Berechenbarkeitstheorie -- Komplexit\"atstheorie},
  isbn = {978-3-446-45793-5},
  langid = {english},
  pagetotal = {431},
  keywords = {LaTeX},
  note = {\begin{quotation}

\par
sdadsafsf
\par
\end{quotation}

\par
PRIME und SAT sind exponenziall ybd gelten in der Praxis als nicht l\"osbar. (\href{zotero://open-pdf/library/items/VAB33DNE?page=30}{note on p.30})
\par

... More notes in similar LaTeX syntax follow ...

}
```
Which gets parsed into Obsidian like this (again only a small snippet is shown):
![image](https://user-images.githubusercontent.com/52347078/131722338-575a546d-c3d0-41cb-a42e-a4a7d0e3eecc.png)

Do you have any idea how to just export the html content of the note? Should I just open a new ticket/feature request with this?

Thanks for your quick replies :+1:

**Comment by hans** [comment]
Hmm, well I see two issues --

1. Zotero Better BibTeX is converting the note content to LaTeX, which seems undesirable given that we're looking to pull the notes into a Markdown database. Maybe there is an option in the extension config, or you can file an issue with the creator? https://github.com/retorquere/zotero-better-bibtex
2. Some of the LaTeX commands are getting rendered as `undefined` during templating. This seems like a bug which I'll look into!

**Comment by puffitos** [comment]
Just wanted to report that it is possible to get raw html in the note of a bib entry: 
```
@inproceedings{kuhrmannHybridSoftwareSystem2017a,
  title = {Hybrid Software and System Development in Practice: Waterfall, Scrum, and Beyond},
  shorttitle = {Hybrid Software and System Development in Practice},
  ... many bib fields follow ...
  note = {<blockquote>
<p>"software development is rich, traditional processes are widely ignored in recent research" (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=2">Kuhrmann et al 2017:31</a>)</p>
</blockquote>
<p>The old plan driven methodologies aren't an active study field, as research focuses mostly on the agile methodologies. (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=2">note on p.31</a>)</p>
<p> </p>
<blockquote>
<p>"Furthermore, we present the data conrming that using hybrid ap- from company size, industry sector, and external standards." (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=2">Kuhrmann et al 2017:31</a>)</p>
</blockquote>
<p>Hybrid approaches seem to have risen in popularity and, as they are flexible in thei use and aren't dependant on company size or type. (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=2">note on p.31</a>)</p>
<p> </p>
<p>Implementation and testing tend to be carried out in a more agile way, regardless of company size or sector. (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=6">note on p.35</a>)</p>
<p> </p>
<blockquote>
<p>"The results show that most of the disciplines are the "best of both worlds"." (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=6">Kuhrmann et al 2017:35</a>)</p>
</blockquote>
<p>Regardless of a company's type and size, a combination of methodologies and development practices seems to be practiced. (<a href="zotero://open-pdf/library/items/GKJF9W2D?page=6">note on p.35</a>)</p>
<p> </p>}
}
```
The better bibtex plugin offers a postscript option, which allows you to edit the .bib entry object (in javascript) before its finally exported. There is an option which allows fields to be parsed as raw html, which even [their documentation](https://retorque.re/zotero-better-bibtex/exporting/scripting/#the-api-for-better-bibtex-and-better-biblatex) characterizes as "useful" for _notes_.

Unfortunately parsing this with your extension produces nothing meaningful :P 
![image](https://user-images.githubusercontent.com/52347078/131891513-a096ba83-25e4-4f86-a345-661c82122505.png)
