### ISSUE TITLE
Get PDF auto-open working

### ISSUE THREAD

**Issue by hans** [hans/obsidian-citation-plugin#12]
First task: find a way to shim PDF URI into Zotero export.

It looks like Better BibTeX supports a BibLaTeX output which includes a `file` key. We can read BibLaTeX with Citation.js, though it doesn't explicitly support BibLaTeX. But the backend can parse BibLaTeX into the corresponding entries, which we can then convert to existing `Entry` constructs.

So I'm thinking we can start supporting BibTeX imports as well as JSON, and support opening PDFs when the `file` element is available.

```javascript
> const Cite = require('citation-js');
undefined
> mystr
'@article{abramowitz1991incumbency,\n' +
  '  title = {Incumbency, {{Campaign Spending}}, and the {{Decline}} of {{Competition}} in {{U}}.{{S}}. {{House Elections}}},\n' +
  '  author = {Abramowitz, Alan I.},\n' +
  '  date = {1991-02-01},\n' +
  '  journaltitle = {The Journal of Politics},\n' +
  '  shortjournal = {The Journal of Politics},\n' +
  '  volume = {53},\n' +
  '  pages = {34--56},  issn = {0022-3816},  doi = {10.2307/2131719},  abstract = {The 1986 and 1988 U.S. House elections set all-time records for reelection of incumbents. This paper proposes and tests a comprehensive model of House election outcomes and uses this model to explain competition for House seats. The results indicate that the extraordinarily low level of competition in recent House elections is directly attributable to two trends which affected these elections during the 1980s: the increasing cost of House campaigns and the declining ability of House challengers to raise campaign funds. After controlling for inflation, a dollar of campaign spending in 1984 or 1986 yielded a much lower rate of electoral return for House challengers than a dollar of campaign spending in 1974 or 1976. In addition, between 1980 and 1988, average spending by House challengers declined by more than 30% in real dollars. Public financing of campaigns could increase competition for House seats, but only if a very high level of funding was provided.},  annotation = {ArticleType: research-article / Full publication date: Feb., 1991 / Copyright © 1991 Southern Political Science Association},  eprint = {2131719},  eprinttype = {jstor},  file = {/home/jon/.dropbox-mit/Dropbox (MIT)/Papers/1991/Abramowitz_1991_Incumbency, Campaign Spending, and the Decline of Competition in U.pdf},  keywords = {campaign finance,politics,to-read},  number = {1}}'
> Cite.parse.bibtex.text(mystr)
[
  {
    type: 'article',
    label: 'abramowitz1991incumbency',
    properties: {
      title: 'Incumbency, {{Campaign Spending}}, and the {{Decline}} of {{Competition}} in {{U}}.{{S}}. {{House Elections}}',
      author: 'Abramowitz, Alan I.',
      date: '1991-02-01',
      journaltitle: 'The Journal of Politics',
      shortjournal: 'The Journal of Politics',
      volume: '53',
      pages: '34–56',
      issn: '0022-3816',
      doi: '10.2307/2131719',
      abstract: 'The 1986 and 1988 U.S. House elections set all-time records for reelection of incumbents. This paper proposes and tests a comprehensive model of House election outcomes and uses this model to explain competition for House seats. The results indicate that the extraordinarily low level of competition in recent House elections is directly attributable to two trends which affected these elections during the 1980s: the increasing cost of House campaigns and the declining ability of House challengers to raise campaign funds. After controlling for inflation, a dollar of campaign spending in 1984 or 1986 yielded a much lower rate of electoral return for House challengers than a dollar of campaign spending in 1974 or 1976. In addition, between 1980 and 1988, average spending by House challengers declined by more than 30% in real dollars. Public financing of campaigns could increase competition for House seats, but only if a very high level of funding was provided.',
      annotation: 'ArticleType: research-article / Full publication date: Feb., 1991 / Copyright © 1991 Southern Political Science Association',
      eprint: '2131719',
      eprinttype: 'jstor',
      file: '/home/jon/.dropbox-mit/Dropbox (MIT)/Papers/1991/Abramowitz_1991_Incumbency, Campaign Spending, and the Decline of Competition in U.pdf',
      keywords: 'campaign finance,politics,to-read',
      number: '1'
    }
  }
]
```

**Comment by Goetterwind** [comment]
One could replace to show the entry in Zotero with
`zotero://open-pdf/library/items/....`

**Comment by hans** [comment]
@Goetterwind Does this work for you with citekeys? That's all we have access to. I was under impression that the `open-pdf` URI only worked with the internal Zotero attachment ID as an identifier.

It doesn't work on my system, but that could well be a bug on my end. I'd be happy to hear that -- would greatly simplify things!

**Comment by hans** [comment]
Yeah, it seems like these URLs don't support looking up by the items, but only by the attachment IDs themselves:

https://github.com/zotero/zotero/blob/master/components/zotero-protocol-handler.js#L1029

**Comment by Goetterwind** [comment]
There must be a way, as zotero knows in which folder they are stored, which is directly the key. 
`zotero://open-pdf/library/items/X4ZFG8 <<< the folder it is stored`

the line 972, 973 also state how to use them (the way it use used in 'Mdnotes for Zotero'. One could glance at that source to see how this is extracted... ;)

**Comment by atomashevic** [comment]
If I may suggest an alternative feature: open citation in Zotero similar to VSCode's [Zotero backward search](https://github.com/ZhiguoLong/vscode-zotero-backward-searcher). 

It would be really helpful to open Zotero when cursor is on page with citekey title or within the page with a citekey title to have an option to quickly open Zotero with the same item selected.

**Comment by hans** [comment]
@atomashevic This is a nice idea. I worry a little about the implementation -- since users have full control over the nature of the literature note titles / Markdown citations, there's no fixed reverse relationship between page content and citation key — in fact, there's no guarantee that the citekey will be present in the content at all.

I suppose we could still just support reverse lookup in the case that the citekey is present, and warn users if they choose reference styles that don't include the citekey. (This reverse lookup idea, and the block to making it work smoothly, is relevant for #22 as well.)

In the short term .. if you're interested in having this feature, you can use the `{{zoteroSelectURI}}` variable in templates to insert a "open in Zotero" link into your documents.

**Comment by hans** [comment]
Regarding PDF auto-open — this is certainly possible with the BibLaTeX export, since zotero-better-bibtex includes file references in their export. This is not a super high priority feature at the moment — I'm prioritizing performance and stability in my own work at the moment.

But if anyone is interested in contributing, that would be very welcome! The relevant changes would involve:

- add `file` properties to the [`EntryData` type and its various adapters](https://github.com/hans/obsidian-citation-plugin/blob/master/src/types.ts#L7), and linking this up to the BibLaTeX `file` property
- add relevant actions to the modal (see https://github.com/hans/obsidian-citation-plugin/blob/master/src/modals.ts#L80)
- do the actual PDF opening (either use [`open`](https://github.com/hans/obsidian-citation-plugin/blob/master/src/modals.ts#L95) to open with system viewer, or maybe open in an Obsidian pane .. ?)

**Comment by atomashevic** [comment]
> In the short term .. if you're interested in having this feature, you can use the `{{zoteroSelectURI}}` variable in templates to insert a "open in Zotero" link into your documents.

Thanks, this is quite handy, completely forgot about this option.

As for the PDFs, the thing I'm doing now is to use ZotFile's 'Send to Tablet' function, where 'tablet storage' is actually papers folder inside my Vault. I use also ZotFile to rename file as `citekey.pdf` so I can quickly find the PDF in Obsidian. The only time I need quick access to PDF in Obsidian is while I'm taking notes (pdf and note side by side) and as soon as I'm done I use ZotFile to remove the file from the Vault and back to Zotero.

Sorry, I know it's not highly relevant for the issue, just wanted to share the workflow.

**Comment by hans** [comment]
Surprise, this was actually added in a recent release! Done.
