### ISSUE TITLE
Obsidian internal links for authorString

### ISSUE THREAD

**Issue by IloveJesusmyKing** [hans/obsidian-citation-plugin#120]
**Is your feature request related to a problem? Please describe.**
No. Just a shortcoming. The current version of the plugin inputs a string of authors with "{{authorString}}". These authors are plain text. I would like each author to be embraced by square brackets because I have individual note files for each author.

**Describe the solution you'd like**
This is an example of what I suggest
- Say an authorString is {John Doe and Sue Smith}
- The citation "Literature note content template" would be something like [[{authorString}}]]
- Then when the literature note is created the result will be [[John Doe]], [[Sue Smith]]

**Describe alternatives you've considered**
Manually entering square brackets

**Additional context**
N/A

**Comment by marcromeyn** [comment]
+1

**Comment by tim-hilde** [comment]
I don't know where I found this, but I use this to get your intended results:

`{{#each entry.author}}[[{{this.given}} {{this.family}}]]{{#unless @last}}, {{/unless}}{{/each}}`

**Comment by IloveJesusmyKing** [comment]
That works! Thank you!

And I would add, if you use the "@" symbol to prefix authors like I do the updated string is like this
`{{#each entry.author}}[[@{{this.given}} {{this.family}}]]{{#unless @last}}, {{/unless}}{{/each}}`
