### ISSUE TITLE
Can't load references

### ISSUE THREAD

**Issue by Kullenej** [hans/obsidian-citation-plugin#121]
Suddenly the plugin can’t read the .bib file? I have the same .bib file that I have used for ages, and I know that it is full of data, but the Citations plugin says it has loaded 0 references! I have tried to do a new automatic export with BetterBibTex in Zotero and pointing the Citations plugin towards the new file, but still nothing. Hope anyone can help!

**Platform**
 - OS: 12.01
 - Obsidian version 0.12.19
 - Plugin version 0.4.4

**Comment by hans** [comment]
Hi, do you see any errors in the Obsidian developer console? See instructions below.

> Please open the Obsidian developer console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>). Click anywhere in the console and force reload Obsidian by typing <kbd>Ctrl</kbd>+<kbd>R</kbd>. Then reproduce the issue you're describing. Please include any relevant error messages that appear in the console in your report here.

In any case -- please also attach your .bib file here so I can try to reproduce the issue on my end.

**Comment by Kullenej** [comment]
I found the issue. I had symbols in some of my references that are probably not allowed. Sorry for the disturbance!
