### ISSUE TITLE
Unable to access literature note whenever I click a citation

### ISSUE THREAD

**Issue by sbacelar** [hans/obsidian-citation-plugin#123]
**Describe the bug**
I have a "Reading notes" folder and I am using Obsidian and Zotero. When I try to access a literature note using ctrl-Shift-O and I choose any citation, e.g. "galassoLessons2003" I receive a message saying that I should upgrade `Citations` (I did) and that the folder `Reading notes` or even `Literature notes` (I tried too) does not exist.

My literature note title template is `{{authorString}}, {{title}}`.

**Console output**
Error: ENOENT: no such file or directory, open 'C:\Users\sbac\iCloudDrive\iCloud~md~obsidian\Reading notes\Vincenzo Galasso, Paola Profeta, Lessons for an Aging Society_ The Political Sustainability of Social Security Systems.md'

I think the problem is that the vault is called `iCloud~md~obsidian`?

**Platform**
 - OS: Windows 10
 - Obsidian version [0.12.19]
 - Plugin version [0.4.4]

**Comment by nleroy917** [comment]
I ran into this today... The issue was that I had specified a Literature note folder in the Settings -> Citations plugin options, but I hadn't already created that folder.
