### ISSUE TITLE
Support fo iPad

### ISSUE THREAD

**Issue by ghost** [hans/obsidian-citation-plugin#132]
Are there any plans for adding support for iOS?
++Johan

**Comment by Benjamin-Lee** [comment]
I tried installing it and was surprised to see it throw an error. I'm keeping my .bib in the workspace and using sync to share it so that I can work with my references on my iPad.

**Comment by arakotoz** [comment]
> I tried installing it and was surprised to see it throw an error. I'm keeping my .bib in the workspace and using sync to share it so that I can work with my references on my iPad.

Hi, I have the same settings and ran in the same issue. It is working well on the Mac though.
Hoping that there will be a future support for iOS,
Cheers

**Comment by vaclavstepan** [comment]
I'd love iOS support too. There seems to be discussion on this topic [here as well](https://githubhot.com/repo/hans/obsidian-citation-plugin/issues/118).

**Comment by hans** [comment]
Closing as a duplicate of #118.
