### ISSUE TITLE
Plugin automatically selects first item from library

### ISSUE THREAD

**Issue by atomashevic** [hans/obsidian-citation-plugin#15]
Reference selection/picker menu does not appear after I either run "Insert citation" or "Open literature note" command.

It automatically chooses the first Zotero item in my JSON file and inserts link or open new literature note.

OS: Ubuntu 20.04
Obsidian: v0.9.22 (deb installer)

Previously (and in previous vault) I used snap version of Obsidian and Citation plugin and selection menu did appear, but nothing happened afterwards. Then I removed the snap version, installed deb and created a new vault.

**Comment by raineszm** [comment]
I'm also seeing this issue.

OS: MacOS 11.1
Obsidian: v0.10.1 (installer 0.9.22)

No errors in the console, although the active leaf appears to be printed.

**Comment by hans** [comment]
Hi both, thanks for the report! Can you please confirm you're on the latest version of the plugin (0.3.0) ?

**Comment by raineszm** [comment]
Yes. This is on 0.3.0.

**Comment by xldenis** [comment]
I'm also getting this issue on the latest version!

**Comment by atomashevic** [comment]
Just to confirm, it's latest version (0.3.0).

**Comment by hans** [comment]
Hmm, I can't reproduce this bug, even with the same Obsidian version and plugin version. Would one of you be willing to share your citation library export?

**Comment by raineszm** [comment]
> Hmm, I can't reproduce this bug, even with the same Obsidian version and plugin version. Would one of you be willing to share your citation library export?

I'd be happy to provide an exported JSON file. I see the problem with my full library which is about 900 items but also with a smaller subset.

[Exported Items.json.txt](https://github.com/hans/obsidian-citation-plugin/files/5717696/Exported.Items.json.txt)

**Comment by atomashevic** [comment]
Here's a smaller subset of my library where I have the same issue.

https://filebin.net/a89izm7wwvd4t8qm

Thanks!

**Comment by hans** [comment]
I'm still failing to reproduce this even with your citation libraries, but I'll try again on a totally clean VM install and keep you posted.

**Comment by raineszm** [comment]
This issue appears to be this event handler https://github.com/hans/obsidian-citation-plugin/blob/7ae75138d6054ff16f5b60fbb96d93d4282ea9c9/src/modals.ts#L24

I think that when calling these functions from the command palette, the event handler is getting the key up of the command submission and immediately submitting the modal. This aligns with the fact that things work fine if I use the assigned hotkeys instead of calling from the command palette.

**Comment by hans** [comment]
@raineszm Thanks a lot for tracking this down. I realize just now that I didn't understand the problem in the first place — I was taking "run command" to mean "run the command via hotkey."

This should be an easy fix -- I'll fix this later today.

**Comment by hans** [comment]
Fixed & will be shipped with the next release, coming very soon. Thanks everyone for pitching in :)
