### ISSUE TITLE
{{URL}} seems to not work anymore

### ISSUE THREAD

**Issue by iGr33k** [hans/obsidian-citation-plugin#159]
**Describe the bug**
{{URL}} variable seems to not work properly with the latest Zotero + Better BibText. Also, upon looking into exported with Better BibText .bib index I noticed that the URL is held inside `howpublished` field, not sure if it was the default behavior before.

**To Reproduce**
1. Generate .bib index with Better Bibxtex  
3. Load index inside the plugin
4. Include {{URL}} variable inside the template
5. Generate new citation with Ctrl+Shitf+O

**Console output**
No relevant messages

**Expected behavior**
In the generated citation note {{URL}} variable would be replaces with the link to a source.

**Platform**
 - OS: Ubuntu
 - Obsidian version 0.14.5
 - Plugin version 0.4.4

**Comment by iGr33k** [comment]
Turns out my Better BibTex preferences changed somehow and "URL" field became disabled.

Closing it now.

**Comment by devonbrackbill** [comment]
If you use Zotero and the Better BibTex package, you need to go to this menu in Zotero and make sure the highlighted options are selected:
<img width="675" alt="Screenshot 2023-11-02 at 8 24 20 AM" src="https://github.com/hans/obsidian-citation-plugin/assets/10455102/21c9cfda-4b20-4f1f-9785-48a67bea3826">
