### ISSUE TITLE
Issue with Accessing Literature Note

### ISSUE THREAD

**Issue by jyrg02** [hans/obsidian-citation-plugin#167]
**Describe the bug**
I am having issues regarding actually using the citations. I am able to import the citations. I have also created a folder for the literature notes
Citation Database: C:\Users\Lenovo\Documents\Degree\Year\Trimester\Course\export.bib
Literature notes folder: C:\Users\Lenovo\Documents\Degree\Notes
**To Reproduce**
When attempting to insert it with Ctrl+Shift+O I get the following 
![image](https://user-images.githubusercontent.com/99687156/169297348-20c1ab8f-618f-4ac7-8beb-bb538beabf15.png)

**Console output**
Please open the Obsidian developer console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>). Click anywhere in the console and force reload Obsidian by typing <kbd>Ctrl</kbd>+<kbd>R</kbd>. Then reproduce the issue you're describing. Please include any relevant error messages that appear in the console in your report here.
![image](https://user-images.githubusercontent.com/99687156/169299551-db33ad0c-9908-407e-ad47-afceca046587.png)

**Expected behavior**
I would expect to happen to get the actual citation
**Screenshots**
Error message: 
![image](https://user-images.githubusercontent.com/99687156/169297348-20c1ab8f-618f-4ac7-8beb-bb538beabf15.png)

**Platform**
 - OS: Windows 10. OS Build 19043.1706
 - Obsidian version; 0.14.06
 - Plugin version: 0.4.4

**Additional context**
This is the following file for .bib that I am trying to insert as citation 
https://docs.google.com/document/d/1xGaHG5Tpr5xOT6NPWJmyR1iSgwdl1_qEClAiN6M6ftY/edit?usp=sharing

**Comment by orionpilot** [comment]
It doesn't look like your note folder is inside the Vault. See this screenshot from the plugin settigns. Try creating a note folder within your Vault. Make sure its already created before trying to create a literature note. 

![image](https://user-images.githubusercontent.com/32915653/169347870-a3a47447-881c-4399-a008-9207f9a26e32.png)

**Comment by jyrg02** [comment]
> It doesn't look like your note folder is inside the Vault. See this screenshot from the plugin settigns. Try creating a note folder within your Vault. Make sure its already created before trying to create a literature note.
> 
> ![image](https://user-images.githubusercontent.com/32915653/169347870-a3a47447-881c-4399-a008-9207f9a26e32.png)

Nope. Doesn't work. Tried what you suggested. Developer console stays the same. 
![image](https://user-images.githubusercontent.com/99687156/169563388-eeafaf50-f764-4539-9f42-8d5db0fe7fe8.png)

Path: C:\Users\Lenovo\Documents\Degree\Year\Trimester\Course\Literature

**Comment by orionpilot** [comment]
What is the path to your Vault? That `Literature` in my example is the path from the Vault root folder. That setting wants a relative path from the Vault root, not an absolute path of the filesystem, like you have. Try leaving that folder entry blank. You should be able to create a note in the root folder.

**Comment by jyrg02** [comment]
> What is the path to your Vault? That `Literature` in my example is the path from the Vault root folder. That setting wants a relative path from the Vault root, not an absolute path of the filesystem, like you have. Try leaving that folder entry blank. You should be able to create a note in the root folder.

That worked! Solved! Thanks!
