### ISSUE TITLE
"Unable to Load Citations"

### ISSUE THREAD

**Issue by micwaab** [hans/obsidian-citation-plugin#168]
**Describe the bug**
Whenever I start Obsidian, I get the error message "Unable to load citations. Please update Citations plugin settings."

**To Reproduce**
1. Open Obsidian
2. Get error message

**Console output**
n/a?

**Expected behavior**
I expect the Citations plugin to load and be useable.

**Screenshots**
<img width="311" alt="image" src="https://user-images.githubusercontent.com/47571490/169540703-73360e73-9a6e-4cce-bd2c-08a93ae00af0.png">

**Platform**
 - OS: MacOS Montery 12.4 (21F79)
 - Obsidian version v0.14.12
 - Plugin version 0.4.4

**Additional context**

**Comment by hdquemada** [comment]
I have the same issue on Obsidian for linux

OS: Linux Ubuntu 20.04.4 LTS
Obsidian version 0.14.6
Plug-in version 0.4.4

I checked the path to my library to make sure it is accurate, but the plug-in can't find it. It works just fine for me on the Mac versions.

**Comment by nmariano9** [comment]
I am getting this same issue! Trying to link Citations plugin to a .json in my Obsidian directory. Was there a resolution found? 

OS: macOS Monterey 12.5
Obsidian version 1.0.0 
Plug-in version 0.4.5

**Comment by gideonite** [comment]
Was this issue resolved? I seem to be having a similar problem but I haven't searched for how to get a more detailed log.

OS: macOS Monterey 12.6
Obsidian Version 1.0.0 (Installer 0.15.9)

Path to library export file is valid but it seems that the plugin is unable to locate it. I am providing an absolute path but when I flip the database format back and forth, I get an error "Please check the path above."

The file is relatively large
```
$ wc zotero_lib.bib
21336  119573  982282 zotero_lib.bib
```

BibLaTeX format. Example entry:

```
@article{abdiPrincipalComponentAnalysis2010,
  title = {Principal Component Analysis},
  author = {Abdi, Hervé and Williams, Lynne J},
  date = {2010},
  journaltitle = {Wiley Interdisciplinary Reviews: Computational Statistics},
  volume = {2},
  number = {4},
  pages = {433--459},
  publisher = {{Wiley Online Library}}
}
```

But there are also, seemingly "bad" entires such as
```
@book{2003,
  date = {2003-01},
  publisher = {{Springer Berlin Heidelberg}},
  location = {{Berlin, Heidelberg}}
}
```

**Comment by pcuellar** [comment]
I was getting the same error, changed to the `.bib` and that file did load properly.
