### ISSUE TITLE
Cannot see the annotations

### ISSUE THREAD

**Issue by szc1fred** [hans/obsidian-citation-plugin#177]
**Describe the bug**
After I import "exported items" from Zotero, I can see the following information, based on my template, but I cannot see my annotations.

This is the template

title: {{title}}
authors: {{authorString}}
year: {{year}}
abstract:{{abstract}}

I tried to add an annotation: {\section{Annotations}}  in the template based on the bib file (see below), but didn't work.

note = {\section{Annotations\\
(6/16/2022, 12:08:44 AM)}

\par
“Augmentative and alternative communication (AAC) is a practical means of communication for people with language disabilities.” (Park et al., 2021, p. 1)
\par

**Expected behavior**
I would like to see my annotations in Obsidian notes.

**Platform**
 - OS: Win11
 - Obsidian version 0.14.15
 - Plugin version 0.4.4

**Additional context**
I am new to the software and appreciate all your help!

**Comment by orionpilot** [comment]
You forgot to add `{{note}}` in your template.

**Comment by szc1fred** [comment]
> You forgot to add `{{note}}` in your template.

Thank you so much!
