### ISSUE TITLE
Figure out more robust library auto-reload

### ISSUE THREAD

**Issue by hans** [hans/obsidian-citation-plugin#19]
On some OSes and some computers the Zotero export triggers quite a few file update events, which means we reload the library quite a few times. Might be best to accumulate these temporally and trigger a reload only when the events stop.

**Comment by masonlr** [comment]
If the json references file changes, does the plugin auto update? i.e. I've got zotero exporting to a local json file with the zotero "Keep updated" option turned on – I'm wondering if I need to quit and reload obsidian in order to bring in the new updates?

When I do a few quick hand edits of the json, I don't think it's currently updating on the obsidian side for me on macOS.

(Thanks for the pugin. It'll be very useful!)

**Comment by hans** [comment]
@masonlr The plugin should auto-update whenever the citation export file updates. If your Zotero changes don't show up, please let me know in an issue report :)

**Comment by Cutuchiqueno** [comment]
For me (Windows 10, Obsidian 10.2 Insiders, Citation plugin 0.3.1) updates of the library only appear after restarting Obsidian. I understand the thread this way that this should have worked already before 0.3.2 (which is not released, is it)?

**Comment by hans** [comment]
Auto-reload was robustified in 3dd325ebe944f39ff4b6cdb4d4b061e88afbedbb . Now there is never more than one simultaneous library reload call happening, even if multiple filesystem events are triggered in quick succession. This should fix performance issues and may affect related loading bugs. Targeted for https://github.com/hans/obsidian-citation-plugin/milestone/2 coming soon.

**Comment by hans** [comment]
The residual Windows issues should be fixed with the release of 0.4.0, happening shortly. If any of you are still experiencing issues after the update, please comment on this issue and I'll reopen it.

**Comment by antoniofabio** [comment]
I have version 0.4.3 installed on linux, and auto-reload does not work for me. I have to manually switch to CSL-JSON and back to BibLaTex to force a reload, which gets old quickly while doing a bibliographic research.

FWIW, my bib file is in a Dropbox folder, under a zfs file system (ubuntu 20.04). Obsidian v0.12.12.

**Comment by antoniofabio** [comment]
I just verified that changing:
`
stabilityThreshold: 500,
`
to
`
stabilityThreshold: 1,
`
in main.ts:113 (from [this commit](https://github.com/hans/obsidian-citation-plugin/blob/35fb8bccb04d4cd9bded853f00141c4cee6e0550/src/main.ts)) fixes the issue for me.
