### ISSUE TITLE
Pull PubMed ID / arbitrary fields from underlying bibtex?

### ISSUE THREAD

**Issue by hbhargava7** [hans/obsidian-citation-plugin#198]
**Is your feature request related to a problem? Please describe.**
Outstanding work with this project. For Life Science / Biomedical research, the Pubmed ID (PMID) / Pubmed Central ID (PMCID) is king. It enables rapid accession, and is also required for things like NIH grants.

It would be great to integrate the ability to pull the `pmid` and `pmcid` fields out of the underlying bibtex file. In fact – I'd love to see the ability to pull arbitrary fields from the bibtex `@ARTICLE` definitions.

**Describe the solution you'd like**
In addition to the list of variables that can be referenced (`citekey`...`zoteroSelectURI`), allow arbitrary handles to be specified that correspond with fields in the bibtex.

**Describe alternatives you've considered**
Workaround could be to run a script to move the PMID / desired field into one of the supported field.s

**Additional context**

**Comment by hbhargava7** [comment]
For what it's worth, I'm using [Paperpile](https://paperpile.com/app) to live generate a bibtex file in Google Drive, which is read into the plugin.

**Comment by hbhargava7** [comment]
Okay resolving my own issue here. From the note in the editor
```
Advanced users may also refer to the {{entry}} variable...
```
I thought this might be possible, but unfortunately there doesn't seem to be a reference on what the structure of `entry` objects looks like or how to explore it.

Thanks to [this post](https://forum.obsidian.md/t/citations-plugin-how-to-access-editor-field/39011/2) I was able to retrieve the object structure from the developer console (by querying `app.plugins.plugins['obsidian-citation-plugin'].library.entries['citekey'].data.creators.editor[0]`, replacing `citekey` with a citekey from my library). This revealed the object structure:

```
creators : 
  author : [] // list of authors
fields : 
  abstract : ...
  doi : ...
  pmc : <PMC ID>
  pmid : <PUBMED ID!>

```

Which made the solution trivial for pubmed id and any other non-exposed fields:

```
{{entry.data.fields.pmid}}
```

This is also very exciting to me because it paves the way for arbitrary field interoperability -- like if paperpile introduces support for exporting their URLs. Now I just need to wrap my head around Handlebars syntax...

**Comment by hbhargava7** [comment]
Tag #44 #42  regarding advanced templating.

**Comment by cchmagyar** [comment]
> 

How are you live generating a bibtex file in Google Drive?

**Comment by hbhargava7** [comment]
> How are you live generating a bibtex file in Google Drive?

See https://paperpile.com/h/automatic-bibtex-export/

Phenomenal feature I didnt know existed till I needed it. Will likely move to github soon if the plugin can take a URL.

**Comment by cchmagyar** [comment]
> > How are you live generating a bibtex file in Google Drive?
> 
> See https://paperpile.com/h/automatic-bibtex-export/
> 
> Phenomenal feature I didnt know existed till I needed it. Will likely move to github soon if the plugin can take a URL.

Sweet.  Thank you!

**Comment by cchmagyar** [comment]
Do you use a template for Obsidian ..annotated bibliography?

**Comment by hbhargava7** [comment]
Not yet — 24h into Obsidian now. Open to recommendations!

**Comment by orionpilot** [comment]
Just highlighting #100 regarding accessing other elements of the underlying bibtex entries. Some variables like `{{abstract}}` have shortcut variables already defined. But if there is a variable within a bibtex entry which does not have a shortcut, like your PMID, then `{{entry.data.fields.FIELD}}` is the way you access it. Looks like you found that answer if a more roundabout way than I did!
