### ISSUE TITLE
Citation import fields with escape

### ISSUE THREAD

**Issue by Seraphli** [hans/obsidian-citation-plugin#202]
**Describe the bug**
I have this template.
```
---
authors: {{authorString}}
year: {{year}}
url: {{URL}}
annotation-target: {{{entry.data.fields.filename}}}
---
Title: {{title}}
Abstract: {{abstract}}
```
The filename is produced by Zotero, with the following postscript.
https://github.com/retorquere/zotero-better-bibtex/discussions/2311
The filename is correct in the bib file.
![image](https://user-images.githubusercontent.com/1586755/202280102-1bfba873-ed0a-450a-8363-a77b023c0cde.png)
But After I try to create a new note with the template. Here is what I get.
![image](https://user-images.githubusercontent.com/1586755/202279529-5a7908dd-3340-4d9e-a588-3d067f7d92cf.png)
So how to fix this? I want this field to be the same as it is in the bib file.

**To Reproduce**
1. Set postscript in Zotero, and export library.
2. Create new note with the template.
3. See error

**Expected behavior**
```
annotation-target: Pan et al_2022_Iso-Dream - Isolating Noncontrollable Visual Dynamics in World Models.pdf
```

**Screenshots**
As above.

**Platform**
 - OS: Win10 LTSC 21H2
 - Obsidian version 1.0.3
 - Plugin version 0.4.5

**Comment by Seraphli** [comment]
This issue is related to the `toJSON` function I think. Because when I change the postscript to replace the `eprint` key instead of creating a new key, the template works fine. I choose the `eprint` key because the data type defined in the abstract class is a string.  I think all `string` type keys will work, if they are pre-defined in the abstract class. Other keys will be added by the `toJSON` function, which causes this problem.

**Comment by dr-cs** [comment]
Try escaping the underscore in your bibliography database (e.g., `.bib` file) with `\`.  `_` is used for subscripts in LaTeX, so I think the `.bib` parser is adding the `<sub></sub>` elements.  I ran into the same issue: Issue #208 .

**Comment by Seraphli** [comment]
@dr-cs I used another way to escape this issue.
