### ISSUE TITLE
Manually paste frontmatter

### ISSUE THREAD

**Issue by tjarkkent** [hans/obsidian-citation-plugin#21]
Hi, 

Would it be possible to create a function to manually paste frontmatter-content? The content could be based on the very same template currently used for literature notes. At least, this would be useful to update existing literature notes, maybe also to create new ones with custom formatting. Calling it from the command palette would be sufficient.

Best,
Tjark

P.S.: Thanks SO MUCH for this plugin! As others have said, it was the last thing missing in Obsidian.

**Comment by hans** [comment]
Great idea! Will add it to the next release.

Happy you're enjoying the plugin.

**Comment by hans** [comment]
Will be released shortly. Thanks for the suggestion!
