### ISSUE TITLE
[HELP] How to seperate the path and file in entry.files

### ISSUE THREAD

**Issue by daamiian** [hans/obsidian-citation-plugin#234]
This is the output:
`Journal Article\\Kahleova et al_2019_Fat Quantity and Quality, as Part of a Low-Fat, Vegan Diet, Are Associated with.pdf`

...for:
`{{entry.files}}`

How can I seperate `Journal Article` and `Kahleova et al_2019_Fat Quantity and Quality, as Part of a Low-Fat, Vegan Diet, Are Associated with.pdf
`

**Comment by anandkumar89** [comment]
you can use `entry.files.[0]`. Works for me!
