### ISSUE TITLE
Cite as You Write Functionality Only?

### ISSUE THREAD

**Issue by JCalinawan** [hans/obsidian-citation-plugin#24]
Hello,

Thank you so much for this plugin! I am wondering if you could consider the following features:

1. I plan to use the plugin to cite as I write. Would it be possible to disable the automatic creation of the literature note? It's usable now as I create a separate folder to hold the notes, but if it could be turned off in the backend based on user selection, that would be great.
2. I use Zettlr to convert markdown to docx, pdf, and HTML. The Zettlr's syntax looks like this [@campbell2011] before the input of page numbers. Is it possible to have a user choice in the backend to output the tag as [[@campbell2011]] OR [@campbell2011]. Even an output without the brackets, @campbell2011, would work as well. Users could type the opening and closing brackets themselves.

Thank you once again for this plugin. I'm looking forward to using it!

Regards,
Jonah

**Comment by hans** [comment]
Hi, thanks for the request! I actually have both features implemented in the codebase but have yet to make a release. Hoping to do that later today. Keep posted for 0.3.2 — hope it works out for you!

**Comment by hans** [comment]
(Actually, just released -- faster than expected. Enjoy!)
