### ISSUE TITLE
Compatibility issue with discordian theme

### ISSUE THREAD

**Issue by jakeoung** [hans/obsidian-citation-plugin#33]
There is a new theme called discordian. Under this theme, if I want to search a reference, I get the following which I couldn't read properly.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/2376897/104067095-d1e83380-5202-11eb-93e0-d8a415a64179.png">

**Comment by hans** [comment]
All set — will push a new release with this fix soon. Thanks for reporting!
