### ISSUE TITLE
Citation plugin BUG

### ISSUE THREAD

**Issue by MartinYuan1995** [hans/obsidian-citation-plugin#35]
My Mac can not recognize .bib document which is transformed from zotero. However, Better CSL JSON can be read, but I can not jump from obsidian to zotero by citation. The page will show metadata(invalid yaml). so could everyone can help me, thanks a lot.

**Comment by hans** [comment]
Hi @MartinYuan1995 , thanks for the report. Looks like there are at least two bugs here?

> My Mac can not recognize .bib document which is transformed from zotero. However, Better CSL JSON can be read

Would you mind uploading the `.bib` file you're using here so I can debug on my side?

> but I can not jump from obsidian to zotero by citation.

What OS are you on? This may be an issue with your Zotero installation, too.

> The page will show metadata(invalid yaml).

Can you please clarify what this means? Is this regarding the `.bib` issue? Or is it a separate problem with the CSL data?

**Comment by MartinYuan1995** [comment]
Hi @hans, thanks for your reply. this is my .bib file which I have uploaded to Google Drive.
https://drive.google.com/file/d/1f_MziYsyq-kZ8Ny-wBPexQX8S9W9Ft-F/view?usp=sharing
when I use cls data, the application could read, but shows metadata (Invalid yaml) like this 
![image](https://user-images.githubusercontent.com/47047658/104113617-699a6e80-5336-11eb-9cfb-a1326ee1d702.png)
finally, thanks for your help and waiting for your reply.

**Comment by hans** [comment]
> when I use cls data, the application could read, but shows metadata (Invalid yaml) like this

That's because your frontmatter is invalid YAML :)

The first line is not valid -- you need a line of the format `key: value`. Change the template line to `citekey: {{citekey}}` perhaps?

**Comment by hans** [comment]
> this is my .bib file which I have uploaded to Google Drive. https://drive.google.com/file/d/1f_MziYsyq-kZ8Ny-wBPexQX8S9W9Ft-F/view?usp=sharing

Hmm, I wasn't able to reproduce the issue -- I can load this `.bib` file just fine and use the plugin with it, no problem.
This might be a platform-specific issue, possibly related to the Chinese characters in the .bib file if I had to guess?

Would you mind helping me debug?
Can you open the Obsidian developer console (Cmd+Shift+I) and attempt to use the `.bib` file with the citations plugin? Let me know what shows up in the developer console when you do this, if anything.

**Comment by MartinYuan1995** [comment]
![image](https://user-images.githubusercontent.com/47047658/104140772-feac6e80-53ed-11eb-95b7-075dd4a66408.png)
thank you, I have solved all problems. it's very strange, the citations can read this .bib file after I updated my citations plugin. 
thanks a lot, you are a good developer with kind.
