### ISSUE TITLE
Unable to access literature note

### ISSUE THREAD

**Issue by kobespecial** [hans/obsidian-citation-plugin#36]
<img width="270" alt="iShot2021-01-10 13 44 01" src="https://user-images.githubusercontent.com/26921752/104115412-2fd36300-534a-11eb-8863-a975011c734b.png">

**Comment by hans** [comment]
Hi, please check that the "Literature notes folder" setting in the
Citations settings points to a folder / path inside your vault which
already exists. (When in doubt, just set this value to be an empty string,
and the literature notes will be placed in the root of the vault.)

If that doesn't fix things, please let me know:

- is this happening for every reference or just some/one?
- what versions of Obsidian and the citation plugin are you using?
- what operating system are you using?
- if you open the Obsidian console (Ctrl+Shift+I) and attempt to open a
literature note as usual, do any messages appear in the console?

**Comment by ontrou** [comment]
I am having the same issue, with the same error message. My notes are in the / root folder.
- it happens for every reference I've tried
- Obsidian v0.10.7, Citations v.0.4.1
- OS Linux
- 
[obsidian.md-1610775531724.log](https://github.com/hans/obsidian-citation-plugin/files/5823907/obsidian.md-1610775531724.log)

**Comment by hans** [comment]
Hi @ontrou , your log suggests that there is a template formatting error.
We don't currently provide the template variable `date` that you're using,
or the custom date formatting trick you used. Remove this `date` line and
things should work!

This brings up two things that could be improved, though:

- more specific error message on note formatting failure
- interoperability with other templating procedures in Obsidian

**Comment by ontrou** [comment]
Thank you @hans . It works well now. I am beginning to grasp that Obsidian plugins have siloed template variables. I'm happy I could up things that could be improved ;-)
