### ISSUE TITLE
Plugin doesn't update with new data in Zotero

### ISSUE THREAD

**Issue by HEmile** [hans/obsidian-citation-plugin#4]
Hi, 
I installed the plugin as you've explained it with BetterBibtex and keep updated. Whenever I add a new resource to Zotero, however, I can't use it in the Obsidian plugin (it doesn't appear). Not sure if this is related to BetterBibtex or the plugin, but I figured it was supposed to work from the description :)

**Comment by hans** [comment]
Right, the database will only be loaded once (when Obsidian is loaded). This is high-priority for me to fix, too!

(A hacky workaround at the moment: refresh Obsidian with <kbd>Ctrl</kbd>-<kbd>R</kbd> to reload the plugin and thus reload the references.)
