### ISSUE TITLE
Error: File already exists when a note with same name exists

### ISSUE THREAD

**Issue by HEmile** [hans/obsidian-citation-plugin#43]
I'm getting 

```
Error: File already exists.
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at a (app.js:1)
```

when inserting a particular literature note for which a note already exists in Obsidian. This is on the test version you sent me.

To reproduce:
- Create a note called "Stochastic Gradient Estimation with Finite Differences"
- Use Zotero extension to add http://approximateinference.org/2016/accepted/BuesingEtAl2016.pdf
- Open it as a literature note. (It does get properly added). 
A notice fires: Unable to open literature note. Please check that the literature folder exists...

**Comment by hans** [comment]
Hi, thanks for reporting! I'm not able to reproduce the problem on a test vault using your procedure.

(I assume you meant "Stochastic Gradient Estimation **w**ith Finite Differences"? And I assume from this step that the citation plugin should be set to create literature note titles with the template `{{title}}`.)

The test vault uses a literature note folder "Reading notes." I tried creating the note beforehand in both (on different attempts) the reading note folder and the vault root — I wasn't sure which one of these you meant.

---

Not sure if it's relevant, but are you using the BibLaTeX format or CSL-JSON format for your library? I think I tested thoroughly with each library type, but I can't see what else could differ between our setups (except vault content of course).

**Comment by HEmile** [comment]
All these assumptions are correct. I use the vault root, myself, as I have no separate folder for this.

I used the CSL-JSON format, as this was what the format was in the first version. I'll be using the BibLaTeX one from now. But in this format it happens, as well. 

Playing around with it a bit, I think the problem is when the capitalization of the Obsidian note is different from the capitalization in the title of the citation.

**Comment by hans** [comment]
Ah! I understand now. Yes, I can reproduce the issue over here. My clarification had a fatal typo -- I actually used the properly cased title ("Estimation **W**ith Finite Differences") in my tests, since that's what my citation entry had.

Anyway, will get to the bottom of this, thanks!

**Comment by hans** [comment]
I discovered that the bug (on my end) at least was due to Dropbox sync, since [Dropbox doesn't allow filenames which only contrast in casing](https://help.dropbox.com/installs-integrations/sync-uploads/case-conflict#:~:text=What's%20a%20Dropbox%20file%20case,records%E2%80%9D%20and%20%E2%80%9CRecords%E2%80%9D.). Disabling Dropbox sync makes the error go away for me (Ubuntu 20.10).

That's not a solution, of course -- will need to think of the right thing to solve this generally..

**Comment by HEmile** [comment]
As mentioned on Discord, I also use Dropbox.
