### ISSUE TITLE
Ability to see prose while selecting citation

### ISSUE THREAD

**Issue by n8craig** [hans/obsidian-citation-plugin#49]
This is a small UI suggestion (enhancement), but I think many writers would appreciate it. **When calling up the citation selector based on a search, it would be nice to still see the text window were writing is taking place**. At present, the citations plugin sits on top of the active window and covers where writing is occurring.
![2021-01-15 17_40_19-Window](https://user-images.githubusercontent.com/62002677/104791672-ccd23980-5758-11eb-95f1-dee1934e13d5.jpg)

Zotero's second generation cite picker is an ok example of what I'm talking about in that it is small and can be moved out of the way if necessary. The Zotero first generation interface was much larger, permits pretty sophistocated searching, and can still be pulled to the side to see the active writing screen. Zettlr's interface is very small, clean, fast and remains at the location of the cursor. However, it suffers from not accepting multi-word input strings which is a big down side. If possible, moving the citation plugin interface in the direction of an unobtrusive small or movable interface would be a really cool improvement--particularly if it was possible to retain the multi-term search function. It think the Obsidian tag selector is a very nice model to consider, though I'm not sure if that interface could deal with multi-word inputs.
![2021-01-15 17_36_06-Window](https://user-images.githubusercontent.com/62002677/104791586-93013300-5758-11eb-9c9f-4e6b1957712a.jpg)

Regardless of any of this, the citation plugin is an outstanding addition to Obsidian. Thanks for all the hard work. I just noticed some templating options you are building into this. Super exciting notion that a writer can configure it to suit their particular preferences; very smart.

**Comment by hans** [comment]
Thanks @n8craig for the thorough suggestion and kind words!
I'm definitely up for this -- the autocomplete-style solution is now on the roadmap. I'll track that at #48.
