### ISSUE TITLE
Include all informations contained in bibtex entry...

### ISSUE THREAD

**Issue by bepolymathe** [hans/obsidian-citation-plugin#55]
Hi, 

Really, thank you very much for this great tool. I have a request about the (many) items in my Zotero that are not PDFs. As a researcher, I need to work on the different sources and the idea of having all my reading notes in Obsidian delights me. But when I integrate a blog post or an article I don't have the corresponding variable. For example [this article](https://legrandcontinent.eu/fr/2021/02/01/conversation-avec-alexei-navalny/)... gives me the following bibtex entry : 

```
@article{gurievConversationAvecAlexei2021,
  title = {Conversation avec Alexeï Navalny, comprendre la doctrine de l'opposant russe},
  author = {Guriev, Sergei},
  date = {2021-02-01T05:00:00+00:00},
  journaltitle = {Le Grand Continent},
  url = {https://legrandcontinent.eu/fr/2021/02/01/conversation-avec-alexei-navalny/},
  urldate = {2021-02-01},
  abstract = {Depuis son retour à Moscou, Alexeï Navalny est en prison. Alors qu’il ne peut pas s’exprimer, nous avons souhaité publier dans les principales langues du débat continental cet entretien de fond avec le dissident russe, qui présente ici son analyse du contexte politique et des perspectives pour le futur de la Russie.},
  entrysubtype = {newspaper},
  file = {/home/manu/Zotero/storage/W4WPHGJG/conversation-avec-alexei-navalny.html},
  langid = {french}
}
```

The "journal title" entry is essential as information and I can't retrieve it.

![image](https://user-images.githubusercontent.com/29939805/106650110-cb937000-6592-11eb-9b70-3be2ca25af4c.png)

Is there a way to fix this problem?

**Comment by hans** [comment]
Hi, you can access this with the variable `{{containerTitle}}`. My apologies for the poor documentation here .. !

**Comment by melsophos** [comment]
And what about the `eprint` field?
