### ISSUE TITLE
Support for markdown links - use link preferences of users

### ISSUE THREAD

**Issue by finn-matti** [hans/obsidian-citation-plugin#57]
As the title says: In my limited use of the plugin it seems that there is no way to set the link format (markdown/wiki) neither is the plugin inferring the link preferences from the link settings of obsidian.

A workaround is to use the [Wikilinks to MDLinks](https://github.com/agathauy/wikilinks-to-mdlinks-obsidian) plugin to change the created links manually, but I'd rather have the citations plugin create appropriate links itself.

**Comment by hans** [comment]
All set -- will be included in the next release!
