### ISSUE TITLE
How to reference the variables location & publisher?

### ISSUE THREAD

**Issue by highnze** [hans/obsidian-citation-plugin#58]
By just typing {{location}} and {{publisher}} to the Literature note template, nothing is shown. 
Anyone any idea?

**Comment by hans** [comment]
Hi, these currently aren't available as template variables, but this is an easy fix. Expect it in a near-future release!

**Comment by highnze** [comment]
Awesome! :)

**Comment by hans** [comment]
In next release, available as `{{publisher}}` and `{{publisherPlace}}` (and also `{{eventPlace}}` for conferences).
