### ISSUE TITLE
What's the difference between the primary and seconary Markdown citation template

### ISSUE THREAD

**Issue by Xunius** [hans/obsidian-citation-plugin#63]
Hi hans,
Thanks for creating this awesome tool.

I'm not quite familiar with the workings of pandoc Markdown citation. I noticed in the settings there are "Markdown primary citation template" and "Markdown secondary citation template". What are the differences? When I call the "insert Markdown citation" command, it seems that the primary one takes effect. When is the secondary one used?

Thanks

**Comment by ctnguyen612** [comment]
Good question!

**Comment by hans** [comment]
Hi, you're free to use these however you want. You can insert the secondary Markdown citation by pressing <kbd>Shift</kbd>+<kbd>Enter</kbd> in the Markdown citation dialog.

The typical use case is

- use the primary citation format for paren-style citations e.g. `[@smith1991]`, which might render as `(Smith, 1991)`
- use the secondary citation format for author-style citations e.g. `@smith1991`, which might render as `Smith (1991)`

You can find information about how these citation styles are treated by Pandoc here: https://pandoc.org/MANUAL.html#extension-citations

**Comment by Xunius** [comment]
@hans 

My bad, I overlooked the Shift+Enter option in the dialog. And thanks for the info regarding Pandoc manual.
I'm closing it.
