### ISSUE TITLE
Request: Add a command to update the bib data

### ISSUE THREAD

**Issue by Benature** [hans/obsidian-citation-plugin#83]
Sometimes I add some new items(e.g. paper) in zotero when the Obisidina is open. I cannot serch the new-added item in `ctrl+shift+O/E`, unless I restart the Obsidian. I guess that it is because the plugin only read the bibtex data when Obsidian.app start, thus I fail to search the item just added. So I wonder if there is a command in `ctrl+P` like "update bibtex data" to re-read the bibtex data would be great, so that I don't need to restart the whole app every time when I want to add a new-added item.

**Comment by Mara-Li** [comment]
There is an another issue (#52) about the non-automatic update of the Bib.

You can update the Bib without restart obsidian with changing the path of the Bib. Usually, I remove and update a letter.

**Comment by Benature** [comment]
thank you @Mara-Li for your cross-reference and your advice as a workaround, though it is still cumbersome but much better than restarting the whole app.
