### ISSUE TITLE
Unable to access literature note whenever I click a citation

### ISSUE THREAD

**Issue by wweatherall** [hans/obsidian-citation-plugin#87]
First of all, I want to tell you that this looks like a super-impressive plug-in. I'm just having some issues with it. 

Below are the screenshots of how this works for me. I'm able to see all my citations, but I've never been able to insert one.

I'm using a .bib file and it is able to find it and the citations in it fine. It just throws the error below when I click one. 

<img width="711" alt="Screen Shot 2021-05-17 at 2 18 41 PM" src="https://user-images.githubusercontent.com/84057259/118552352-112c1100-b71c-11eb-9971-88635eec175f.png">
<img width="347" alt="Screen Shot 2021-05-17 at 2 18 14 PM" src="https://user-images.githubusercontent.com/84057259/118552367-138e6b00-b71c-11eb-9218-5a7dc9f7f29d.png">

this is an example entry from my bib file:

```
@article{mal14,

	author = {Malle, Bertram F and Guglielmo, Steve and Monroe, Andrew E},

	date-added = {2021-05-09 10:00:21 -0600},

	date-modified = {2021-05-09 10:00:26 -0600},

	journal = {Psychological Inquiry},

	number = {2},

	pages = {147--186},

	publisher = {Taylor \& Francis},

	title = {A theory of blame},

	volume = {25},

	year = {2014}}
```

thanks, 

Will

**Comment by hans** [comment]
Hi, what do your Citations plugin settings look like? By default the plugin will look for a folder called "Reading notes" and will show this error if the folder does not exist. You can change that in the settings dialog.

**Comment by wweatherall** [comment]
I see. I made a typo when creating the folder. 😬

Thank you so much for your help
