### ISSUE TITLE
New citations doesnt show up in citationpicker - only when i let bib-file be reread

### ISSUE THREAD

**Issue by benytzlich** [hans/obsidian-citation-plugin#98]
I use zotero + BetterBibtex. New citations automatically update. I used .json and .bib files. 

the obsidian citation plugin apparently doesnt pick up the new bibliography. It only works when I manipulate the directory of the Bibliography and then switch back to my filepath- > only then the plugin seems to reads out the newly added citations...

Any idea?

**Comment by csducate** [comment]
I have been having a similar problem. It probably began in the last month.

**Comment by benytzlich** [comment]
yes, I just had issues with that recently.  Zotero and betterbibtex are updated. 

The bibfile itself is fine too!

**Comment by PortfolioProgramProjectManagement** [comment]
I closed Obsidian; start again and all the new updates were here!

Hope it's helping!

**Comment by hans** [comment]
Hi all, there should be a fix for this issue in the just-released [v0.4.4](https://github.com/hans/obsidian-citation-plugin/releases/tag/0.4.4). Please update and let me know here if the issue is not resolved for you. Thanks for your extreme patience!
